# These are supported funding model platforms

github: [AmarjeetJyotis]
patreon: 
open_collective: Personal-Portfolio-Website
ko_fi: 
tidelift: 
community_bridge: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
custom: []
